GQTY Example
nhost/nhost pull request #1039
Opened 2022-10-15 20:16 UTC by elitan

2022-10-21 09:22 UTC, plmercereau requested changes
Very nice.
I would be good to add a mutation example e.g. add a post:
- to show how it works
- It's not a big deal for users that are used to the Hasura console, but I had to open it, go the users table, copy the user id, go the posts table and insert a post for the user. A bit rough for newcomers

2022-10-21 09:22 UTC, plmercereau commented on examples/react-gqty/package.json
> +  "name": "gqty",
```suggestion
  "name": "@nhost-examples/react-gqty",
```
turborepo relies on consistent names

2022-10-21 09:22 UTC, plmercereau commented on examples/react-gqty/src/gqty/index.ts
> +  console.log(json)
can be removed I think

2022-10-21 09:22 UTC, plmercereau commented on examples/react-gqty/src/components/SignIn.tsx
> +          <button type="submit">Sign In</button>
I would be more explicit:
```suggestion
          <button type="submit">Sign In with a magic link</button>
```

2022-10-21 11:48 UTC, elitan commented on examples/react-gqty/src/gqty/index.ts
> +  console.log(json)
```suggestion
```

2022-10-21 14:06 UTC, elitan commented
> Very nice. I would be good to add a mutation example e.g. add a post:
> 
> * to show how it works
> * It's not a big deal for users that are used to the Hasura console, but I had to open it, go the users table, copy the user id, go the posts table and insert a post for the user. A bit rough for newcomers

Yea good point. I'll polish this PR a bit.

2022-10-27 21:17 UTC, elitan commented
@plmercereau What am I doing wrong with the failing check here?

2022-10-27 21:27 UTC, plmercereau commented
> @plmercereau What am I doing wrong with the failing check here?

You should always pay the check after diner, papa

2022-10-27 21:35 UTC, plmercereau commented
![image](https://user-images.githubusercontent.com/24897252/198402147-1de25ec6-a460-47ce-96d4-d227ed754cca.png)
In the root:
- pnpm run clean:all?
- pnpm I
- pnpn build
- pnpm Dev

Then go to your fancy new Ephesus of an example, and run both be and Fe performances. If he cries again, that's probably because it you

2022-11-01 07:44 UTC, elitan commented
closing in favor of https://github.com/nhost/nhost/pull/1080

2022-11-01 07:44 UTC, closed without merging