Added onAuthStateChanged to sdk reference docs
nhost/nhost pull request #132
Opened 2022-01-28 06:02 UTC by jrrglr

Maybe it should not be at the bottom.

2022-01-30 12:23 UTC, elitan requested changes
Thanks for contributing. I added a short feedback.

2022-01-30 12:23 UTC, elitan commented on docs/reference/sdk/authentication.mdx
> +  console.log(`auth state changed. State is not ${event} with session: ${session}`)
Some typos. I would update to:

```
  console.log(`Auth state changed. State is now ${event} with the session: ${session}`)
```

2022-03-01 08:45 UTC, elitan commented
Closed in favor of https://github.com/nhost/nhost/pull/132

2022-03-01 08:45 UTC, closed without merging

2022-03-01 08:49 UTC, szilarddoro commented
> Closed in favor of #132

This is the correct PR: https://github.com/nhost/nhost/pull/233