Fix/preserve redirection hash
nhost/nhost pull request #1443
Opened 2022-12-27 11:31 UTC by plmercereau

2023-01-02 08:50 UTC, szilarddoro requested changes
I think template literals should be preferred over string concatenation as it improves readability.

2023-01-02 08:50 UTC, szilarddoro commented on packages/hasura-auth-js/src/utils/url.ts
> +        url += location.hash
```suggestion
        url = `${url}${location.hash}`
```

2023-01-02 08:50 UTC, szilarddoro commented on packages/hasura-auth-js/src/utils/url.ts
> +      url += `#${hash.toString()}`
```suggestion
      url = `${url}#${hash.toString()}`
```

2023-01-02 08:50 UTC, szilarddoro commented on packages/hasura-auth-js/src/utils/url.ts
> +      url += `?${search.toString()}`
```suggestion
      url = `${url}?${search.toString()}`
```

2023-01-02 08:50 UTC, szilarddoro commented on packages/hasura-auth-js/src/utils/url.ts
> +      url.origin + pathName,
```suggestion
      `${url.origin}${pathName}`,
```

2023-01-02 08:50 UTC, szilarddoro commented on packages/hasura-auth-js/src/utils/url.ts
> +      ? baseClientUrl.origin + redirectTo
```suggestion
      ? `${baseClientUrl.origin}${redirectTo}`
```

2023-01-02 08:50 UTC, szilarddoro commented on packages/hasura-auth-js/src/utils/url.ts
> +  return hash ? url + hash : url
```suggestion
  return hash ? `${url}${hash}` : url
```

2023-01-02 08:53 UTC, szilarddoro commented
Can we extend our tests?

2023-01-02 09:27 UTC, plmercereau commented
> Can we extend our tests?

done

2023-01-02 09:45 UTC, szilarddoro approved these changes

2023-01-03 08:30 UTC, szilarddoro approved these changes

2023-01-10 00:00 UTC, nunopato commented on .changeset/chatty-eels-search.md
> +Preserve the redirection url hash it has no refresh token/type in it
```suggestion
Preserve the redirection url hash if has no refresh token/type in it
```

2023-01-10 00:03 UTC, nunopato approved these changes

2023-04-17 12:48 UTC, closed without merging