feat(dashboard): Retrigger Deployments
nhost/nhost pull request #1503
Opened 2023-01-11 09:40 UTC by szilarddoro

2023-01-11 11:44 UTC, guicurcio requested changes

2023-01-11 11:44 UTC, guicurcio commented on dashboard/src/components/applications/AppDeployments.tsx
> +                isLive={liveDeploymentId === deployment.id}
Thanks for merging these components together. But should we even show the redeploy button here? I think it looks a bit too crowded:  
  
 

![](https://user-images.githubusercontent.com/20285232/211797601-6e4284b0-3b8b-4c95-83f8-1ceec9cf8325.png)

2023-01-11 11:44 UTC, guicurcio commented on dashboard/src/components/deployments/DeploymentListItem/DeploymentListItem.tsx
> +        <div className="flex cursor-pointer flex-row items-center justify-center space-x-2 self-center">
Can we add some variants for mobile?

2023-01-11 11:44 UTC, guicurcio commented on dashboard/src/components/deployments/DeploymentListItem/DeploymentListItem.tsx
> +        <div className="flex cursor-pointer flex-row items-center justify-center space-x-2 self-center">
![](https://user-images.githubusercontent.com/20285232/211797792-fe94b262-9d0b-4940-aea2-52c37df778d3.png)

![2023-01-11 08_38_01-Nhost Netlify Starter Template - Nhost](https://user-images.githubusercontent.com/20285232/211797841-e80fb722-5662-415a-a6c6-237b2fc6abb4.png)

I think that hiding the commit sha and the time should be good wdyt?

2023-01-12 01:34 UTC, guicurcio approved these changes
Given that most of the required changes are actually design-based (and were not part of this project) I think we could merge this and then make those cosmetic changes :thinking:

2023-01-12 01:35 UTC, guicurcio commented on dashboard/src/components/deployments/DeploymentListItem/DeploymentListItem.tsx
> +        <div className="flex cursor-pointer flex-row items-center justify-center space-x-2 self-center">
Szilard, I think we could convert both of these into issues and come back later when the designs are ready

2023-01-12 09:22 UTC, szilarddoro commented
Created an issue for this design improvement: https://github.com/nhost/nhost/issues/1510

2023-01-12 11:41 UTC, merged