feat: Add generic types for NhostClient request method return type and variables
nhost/nhost pull request #407
Opened 2022-04-13 13:18 UTC by hajek-raven

Add generic types for NhostClient request return type and variables. This improves developer experience.

(My first PR in this project 🎉 )

2022-04-13 14:20 UTC, szilarddoro reviewed
Your PR is greatly appreciated @hajek-raven! Congrats on your **first one** for Nhost 🎉

Let me know what you think about my suggestions.

2022-04-13 15:51 UTC, hajek-raven commented on packages/nhost-js/src/clients/graphql.ts
> +    responseData = responseData as GraphqlResponse<T>
Thank you for your feedback!

I decided to refactor the code as it is was chaotic. I got rid of the responseData in outer context altogether.

2022-04-13 15:57 UTC, hajek-raven commented on packages/nhost-js/src/clients/graphql.ts
> +    responseData = responseData as GraphqlResponse<T>
I think I'd be a good idea to refactor this class a bit further (improve testability).
One opportunity might be to add the ability to provide custom axios instance. Or maybe abstract the network library altogether, but that should be handeled in different PR. 😄

2022-04-14 08:27 UTC, szilarddoro requested changes

2022-04-14 08:27 UTC, szilarddoro commented on packages/nhost-js/src/clients/graphql.ts
> +          ...(variables ? { variables } : {})
For the sake of readability we can rather use `variables: variables || {}` here. I don't worry about having a `variables: {}` passed to the Axios POST call.

2022-04-14 08:27 UTC, szilarddoro commented on packages/nhost-js/src/clients/functions.ts
> +  async call<T = unknown, D = any>(url: string, data: D, config?: AxiosRequestConfig): Promise<FunctionCallResponse<T>> {
You did a good job on refactoring the `request` function in `graphql.ts`. 👍🏼 

Could you please apply the same changes to this function too? Then I think we are good to go.

2022-04-14 08:29 UTC, szilarddoro commented on packages/nhost-js/src/clients/graphql.ts
> +    responseData = responseData as GraphqlResponse<T>
Definitely agree 👍🏼 Don't hesitate to open an issue with your enhancement proposals. We can discuss the matter there.

2022-04-19 07:21 UTC, szilarddoro approved these changes

2022-04-19 07:22 UTC, merged

2022-04-19 07:24 UTC, szilarddoro commented
Awesome 👍🏼  Thank you for your help @hajek-raven!