Docs: Updated inline docs
nhost/nhost pull request #558
Opened 2022-05-16 11:23 UTC by elitan

2022-05-16 11:26 UTC, plmercereau approved these changes

2022-05-17 10:31 UTC, plmercereau requested changes

2022-05-17 10:31 UTC, plmercereau commented on packages/react/src/hooks/common.ts
> +/**
`useSignOut` tsdoc is declared twice

2022-05-17 10:31 UTC, plmercereau commented on packages/react/src/hooks/common.ts
> + *   const isAutenticated = useAuthenticated()
`isAutenticated` -> `isAuthenticated`

2022-05-17 10:31 UTC, plmercereau commented on packages/react/src/hooks/registration.ts
> + * Use the hook `useSIgnUpEmailPassword` to sign up a user using email and password.
`useSIgnUpEmailPassword` -> `useSignUpEmailPassword`

2022-05-17 10:52 UTC, szilarddoro commented on docs/docs/reference/docgen/javascript/storage/content/hasura-storage-client/content/01-upload.mdx
> +custom_edit_url: https://github.com/nhost/nhost/edit/main/packages/hasura-storage-client.ts#L41
Something is not right with storage edit URLs. They are not pointing to `packages/hasura-storage-js/src/hasura-storage-client.ts` file.

2022-05-17 10:52 UTC, szilarddoro commented on docs/docs/reference/docgen/javascript/storage/content/hasura-storage-client/content/01-upload.mdx
> +Use `nhost.storage.upload` to upload a file. The `file` must be of type `File` (https://developer.mozilla.org/en-US/docs/Web/API/File).
```markdown
[`File`](https://developer.mozilla.org/en-US/docs/Web/API/File)
```

2022-05-17 10:52 UTC, szilarddoro commented on packages/react/src/hooks/authentication.ts
> + *  Use the hook `useProviderLink` to get a OAuth provider URL that can be used to sign in users.
```diff
- a OAuth
+ an OAuth
```

2022-05-17 10:52 UTC, szilarddoro commented on packages/react/src/hooks/user.ts
> + * Use the hook `useSendVerificationEmail` to send a verification email. The verification email is sent to the user's email address and inclides a link to verify the email address.
```diff
- inclides
+ includes
```

2022-05-17 10:55 UTC, szilarddoro commented on packages/hasura-auth-js/src/hasura-auth-client.ts
> +   * nhost.auth.signIn({
`nhost.auth.signUp`

2022-05-17 12:23 UTC, szilarddoro approved these changes
🦾

2022-05-17 12:36 UTC, merged