feat: new `adminSecret` option
nhost/nhost pull request #609
Opened 2022-05-27 17:14 UTC by plmercereau

close #193

2022-05-27 17:42 UTC, elitan requested changes
Nice! Small copy changes.

In the future, I think we should add methods for interacting with users as admin too. Like:

```
nhost.auth.admin.createUser()
nhost.auth.admin.updateUser()
nhost.auth.admin.deleteUser()
```

2022-05-27 17:42 UTC, elitan commented on packages/hasura-storage-js/src/hasura-storage-client.ts
> +   * Hasura storage endpoint.
Storage endpoint

2022-05-27 18:27 UTC, plmercereau commented
> Nice! Small copy changes.
> 
> In the future, I think we should add methods for interacting with users as admin too. Like:
> 
> ```
> nhost.auth.admin.createUser()
> nhost.auth.admin.updateUser()
> nhost.auth.admin.deleteUser()
> ```

Yes, we should think of a way to implement this without increasing the complexity of our code nor bypassing the existing workflows (for instance email verification)

2022-05-27 19:34 UTC, elitan approved these changes

2022-05-27 19:50 UTC, merged

2022-05-31 21:28 UTC, st3phan commented
@plmercereau I tried this new `adminSecret` option in my functions set up and it works.
But in my use case when using `nhost.graphql.request` I sometimes want to overwrite the authorization headers with client headers that are forwarded to the webhook by hasura.
When I do it seems that the authorization headers are ignored.

In code:
```ts
export const nhost = new NhostClient({
  backendUrl: process.env.NHOST_BACKEND_URL,
  adminSecret: process.env.NHOST_ADMIN_SECRET
});

const { data, error } = await nhost.graphql.request(
  DOCUMENT,
  {
    headers: {
      authorization: req.headers.authorization, // Looks like this is ignored because of the `adminSecret` that is set
      'x-hasura-user-id': req.session_variables['x-hasura-user-id'],
    },
  },
);
```

2022-05-31 21:37 UTC, plmercereau commented
> @plmercereau I tried this new `adminSecret` option in my functions set up and it works. But in my use case when using `nhost.graphql.request` I sometimes want to overwrite the authorization headers with client headers that are forwarded to a webhook by hasura. When I do it seems that the authorization headers are ignored.
> 
> In code:
> 
> ```ts
> export const nhost = new NhostClient({
>   backendUrl: process.env.NHOST_BACKEND_URL,
>   adminSecret: process.env.NHOST_ADMIN_SECRET // I want to use the adminSecret for all requests except when I set custom headers
> });
> 
> const { data, error } = await nhost.graphql.request(
>   DOCUMENT,
>   {
>     headers: {
>       authorization: req.headers.authorization, // Looks like this is ignored because of the `adminSecret` that is set
>       'x-hasura-user-id': req.session_variables['x-hasura-user-id'],
>     },
>   },
> );
> ```

I'm repopening the issue and will take some time for reproduction and analysis.
Will keep you posted

Thanks mate

2022-06-30 19:56 UTC, st3phan commented
@plmercereau any update on this?

2022-10-31 20:26 UTC, GavanWilhite commented
@st3phan @plmercereau End up figuring anything out here?