Unauthenticated users bag
nhost/nhost pull request #635
Opened 2022-05-31 09:11 UTC by Meir-p

Prevent from unauthenticated users from always receiving error (Because there is no id)

2022-05-31 14:02 UTC, elitan commented
@gdangelo Would you mind checking this PR?

2022-05-31 14:09 UTC, Meir-p commented
@elitan It actually didn’t fix it but I will add a video Of the problem:
https://user-images.githubusercontent.com/100231666/171193567-ecf383d0-b475-4991-844f-bbb296a2443c.mov

2022-05-31 14:15 UTC, Meir-p commented on docs/docs/platform/quickstarts/nextjs.mdx
> +    const { loading, error, data } = useQuery(GET_USER_QUERY, {
definitely right

2022-06-01 08:48 UTC, gdangelo commented
> @gdangelo Would you mind checking this PR?

Sure! I'm looking at it.

2022-06-01 09:23 UTC, gdangelo commented on docs/docs/platform/quickstarts/nextjs.mdx
> +    const { loading, error, data } = useQuery(GET_USER_QUERY, {
I agree. The best solution is to check if the `id` variable is not falsy before running the GraphQL query. 

As @plmercereau said, the Apollo client provides a `skip` option to don't execute the query if this option is `true`.

@Meir-p could you please update your PR with the following code instead?

```js
const id = useUserId();
const { loading, error, data } = useQuery(GET_USER_QUERY, {
  variables: { id },
  skip: !id,
});
```

Thanks

2022-06-01 09:26 UTC, gdangelo requested changes
No need to use the `useAuthenticationStatus` hook.

We can simply check the `id` variable returned by the `useUserId` hook. If it is falsy, then we don't run the GraphQL query using the `skip` option.

@Meir-p could you please revert your changes and add the `skip` option to the `useQuery` call?

```js
const id = useUserId();
const { loading, error, data } = useQuery(GET_USER_QUERY, {
  variables: { id },
  skip: !id,
});
```

2022-06-02 07:22 UTC, gdangelo commented
Finally, I've created a new PR for this issue → #659

2022-06-02 19:52 UTC, plmercereau commented
@Meir-p many thanks for raising up the issue and for helping us to adjust the quickstart!
Thanks Grégory too!
Closing the PR

2022-06-02 19:52 UTC, closed without merging