test: change email and password
nhost/nhost pull request #711
Opened 2022-06-15 08:04 UTC by plmercereau

2022-06-16 13:03 UTC, szilarddoro requested changes

2022-06-16 13:42 UTC, plmercereau commented on examples/react-apollo/cypress/e2e/4-authenticated/change-password.cy.ts
> +context('Change password', () => {
ditto

2022-06-16 14:27 UTC, szilarddoro commented on examples/react-apollo/cypress/e2e/4-authenticated/change-email.cy.ts
> +context('Change email', () => {
I agree that we should create smaller PRs, but I think it makes sense to add them in this PR, not in a separate one, because they belong together.

2022-06-17 12:16 UTC, szilarddoro approved these changes

2022-06-17 12:22 UTC, merged