Use :1337 if no port is specified when using "localhost"
nhost/nhost pull request #786
Opened 2022-07-04 00:16 UTC by nunopato

- use :1337 when a port is not specified when using ''localhost"

2022-07-04 08:04 UTC, plmercereau requested changes
Please add a changeset

2022-07-04 08:06 UTC, plmercereau commented
subdomain: 'localhost:1234' is somehow semantically incorrect. We can live with it, but I think we should introduce a `port` param at a later stage, that would default to `1337` when `subdomain` equals `'localhost'`

2022-07-05 05:04 UTC, elitan commented
Update potential docs that currently use `localhost:1337` to `localhost`. Either after merging or in this PR.

https://github.com/nhost/nhost/pull/783#pullrequestreview-1027664862

2022-07-13 04:46 UTC, elitan commented
> subdomain: 'localhost:1234' is somehow semantically incorrect. We can live with it, but I think we should introduce a `port` param at a later stage, that would default to `1337` when `subdomain` equals `'localhost'`

This should work because there are developers who are using `subdomain: 'localhost:1337'` with the current version and things should not break for them just because of this update.

2022-07-13 04:50 UTC, elitan requested changes

2022-07-13 04:50 UTC, elitan commented on packages/nhost-js/src/utils/helpers.ts
> +      : `http://${backendOrSubdomain.subdomain}/v1/${service}`
For developers who are currently using `localhost:1337` this update will break their code.

I think we should allow for `localhost:<port>` here. Something like this:


```js
return backendOrSubdomain === 'localhost'
      ? `http://localhost:1337/v1/${service}`
      : backendOrSubdomain.startsWith('localhost:') (or regex) 
        ? `http://${backendOrSubdomain}/v1/${service}` 
        : `http://${backendOrSubdomain.subdomain}/v1/${service}`
```

2022-08-22 19:45 UTC, plmercereau commented
`examples/react-apollo/cypress/videos/1-unauthenticated/authentication-guards.cy.ts.mp4` etc should not be pushed

2022-08-22 19:59 UTC, elitan commented
> `examples/react-apollo/cypress/videos/1-unauthenticated/authentication-guards.cy.ts.mp4` etc should not be pushed

Should be fixed here: https://github.com/nhost/nhost/pull/786/commits/9feea987e68a3be00c8bc860d1e16fff7193bc59

2022-08-22 20:05 UTC, plmercereau commented on packages/nhost-js/src/utils/helpers.ts
> +  if (subdomainLocalhostFound && subdomainLocalhostFound.length > 0) {
could be simplified by
```js
if (LOCALHOST_REGEX.test(subdomain)
```

2022-08-22 20:13 UTC, plmercereau approved these changes

2022-08-22 20:17 UTC, elitan approved these changes

2022-08-22 20:18 UTC, merged